apiVersion: skaffold/v1beta6
kind: Config
build:
  artifacts:
  - image: sandbox/fluentd
    context: .
    docker:
      dockerfile: ./Dockerfile
  tagPolicy:
    gitCommit: {}
  local:
    push: false
    useDockerCLI: true
deploy:
  kubectl:
    manifests:
    - ./fluentd-daemonset.yaml
